/**
 * The `[editor]` half of the theme contract, exercised against the real
 * `applyTheme` and the real serde output.
 *
 * ## Why this file exists separately
 *
 * `theme.test.ts` builds its `ThemeData` by hand, in snake_case, with
 * `editor: null`. That fixture agreed with `src/lib/types/index.ts` by
 * construction, so it asserted the TypeScript type against itself and
 * stayed green for as long as the Rust side was serializing `added-bg`,
 * `syntax-keyword`, `gutter-fg` — kebab-case, from `#[serde(rename)]`,
 * which changes serialization as well as deserialization. Every read of
 * `ed.added_bg` was `undefined`, so all 15 `[editor]` tokens of every
 * theme were inert and diff backgrounds fell through to the DARK defaults
 * in `app.css`, in light themes too.
 *
 * The fixture here is generated by
 * `storage::theme::tests::regenerate_theme_fixture` and pinned by
 * `test_theme_fixture_matches_live_serialization`, so these assertions run
 * against the exact bytes the frontend receives over IPC.
 *
 * Two themes, deliberately: `beardgit-light` is the light-mode default
 * where the bug was visible, but only one of its syntax colors differs
 * from the fallback it would collapse to, so it has thin signal on that
 * axis. `github-light` is the only light theme shipping a pinned
 * `[editor]` block and differs on four.
 */

import { beforeEach, describe, expect, it } from "vitest";
import type { ThemeData } from "../types";
import { applyTheme } from "./theme";
import fixtures from "./__fixtures__/themes.json";

// A plain annotation, deliberately not `as unknown as`: this line is the
// strongest guard in the file. If the fixture regresses to kebab-case keys,
// `npm run check` fails with "missing the following properties from type
// 'ThemeEditorData': added_bg, syntax_keyword, …" before any test runs. A
// cast here would throw that away and leave only the runtime assertions.
const themes: Record<string, ThemeData> = fixtures;
const THEME_IDS = ["beardgit-light", "github-light"] as const;

/** Read a custom property off the documentElement's inline style. */
function token(name: string): string {
  return document.documentElement.style.getPropertyValue(name);
}

/** The derived fallback `applyTheme` uses for each syntax token. */
function syntaxFallbacks(theme: ThemeData): Record<string, string> {
  const d = theme.derived;
  return {
    syntax_keyword: d.accent_red,
    syntax_string: d.accent_green,
    syntax_comment: d.text_secondary,
    syntax_function: d.accent_purple,
    syntax_type: d.accent_blue,
    syntax_number: d.accent_orange,
    syntax_operator: d.accent_red,
    syntax_property: d.accent_blue,
  };
}

beforeEach(() => {
  document.documentElement.removeAttribute("style");
});

describe("theme fixture — the shape the frontend actually receives", () => {
  it("contains both themes, in light mode, with editor sections", () => {
    // Guards everything below: a fixture that lost a theme or its editor
    // section would make the colour assertions vacuous.
    expect(Object.keys(themes).sort()).toEqual([...THEME_IDS].sort());
    for (const id of THEME_IDS) {
      expect(themes[id].meta.mode, id).toBe("light");
      expect(themes[id].editor, id).not.toBeNull();
    }
  });

  it.each(THEME_IDS)("names every %s editor key in snake_case", (id) => {
    // The exact failure mode: `added-bg` here means `ed.added_bg` is
    // `undefined` in `applyTheme`, silently.
    const keys = Object.keys(themes[id].editor!);
    expect(keys).not.toHaveLength(0);
    for (const key of keys) {
      expect(key).not.toContain("-");
    }
  });

  it.each(THEME_IDS)("exposes %s's required fields as hex strings", (id) => {
    const ed = themes[id].editor!;
    for (const field of [
      "background",
      "foreground",
      "cursor",
      "selection",
      "added_bg",
      "removed_bg",
      "added_text",
      "removed_text",
      "line_highlight",
      "gutter_bg",
      "gutter_fg",
    ] as const) {
      expect(ed[field], `${id}.editor.${field}`).toMatch(
        /^#[0-9a-fA-F]{3,8}$/,
      );
    }
  });

  it("has github-light syntax colors that differ from their fallbacks", () => {
    // Without this, "applies pinned syntax colors" below could pass against
    // a broken read: when every `ed[field]` is `undefined`, both sides of
    // that assertion collapse to the fallback.
    //
    // `!= null` is load-bearing — it rejects `undefined` as well as `null`.
    // With `!== null` this guard was itself vacuous, because `undefined`
    // satisfies both halves of the predicate and every field would count
    // as "differing" under exactly the fixture shape it exists to reject.
    const theme = themes["github-light"];
    const ed = theme.editor!;
    const fallbacks = syntaxFallbacks(theme);
    const differing = Object.entries(fallbacks).filter(([field, fallback]) => {
      const pinned = ed[field as keyof typeof ed];
      return pinned != null && pinned !== fallback;
    });
    expect(differing.length).toBeGreaterThan(0);
  });
});

describe("applyTheme — editor tokens reach the CSS custom properties", () => {
  it.each(THEME_IDS)(
    "%s writes its own diff backgrounds, not the app.css dark defaults",
    (id) => {
      // This is the bug from bug_images/theme_discrepancy.png: the guard
      // `if (ed?.added_bg)` never fired, so these two kept the dark values
      // `#2a3120` / `#39201c` baked into app.css.
      const theme = themes[id];
      applyTheme(theme);

      expect(token("--diff-added-bg")).toBe(theme.editor!.added_bg);
      expect(token("--diff-removed-bg")).toBe(theme.editor!.removed_bg);
      expect(token("--diff-added-bg")).not.toBe("#2a3120");
      expect(token("--diff-removed-bg")).not.toBe("#39201c");
    },
  );

  it.each(THEME_IDS)("%s applies pinned syntax colors, else the fallback", (id) => {
    const theme = themes[id];
    const ed = theme.editor!;
    const fallbacks = syntaxFallbacks(theme);
    applyTheme(theme);

    for (const [field, fallback] of Object.entries(fallbacks)) {
      const pinned = ed[field as keyof typeof ed] as string | null;
      const cssName = `--${field.replace("_", "-")}`;
      expect(token(cssName), `${id} ${cssName}`).toBe(pinned ?? fallback);
    }
  });

  it.each(THEME_IDS)("%s writes the gutter and cursor tokens", (id) => {
    const theme = themes[id];
    const ed = theme.editor!;
    applyTheme(theme);

    expect(token("--editor-line-highlight")).toBe(ed.line_highlight);
    expect(token("--editor-gutter-bg")).toBe(ed.gutter_bg);
    expect(token("--editor-gutter-fg")).toBe(ed.gutter_fg);
    expect(token("--editor-cursor")).toBe(ed.cursor);
    expect(token("--editor-selection")).toBe(ed.selection);
  });

  it.each(THEME_IDS)("%s writes the diff text colors", (id) => {
    const theme = themes[id];
    applyTheme(theme);

    expect(token("--diff-added-text")).toBe(theme.editor!.added_text);
    expect(token("--diff-removed-text")).toBe(theme.editor!.removed_text);
  });

  it("switching themes replaces the diff backgrounds rather than keeping them", () => {
    // The two themes must differ here, or this proves nothing.
    const a = themes["beardgit-light"];
    const b = themes["github-light"];
    expect(a.editor!.added_bg).not.toBe(b.editor!.added_bg);

    applyTheme(a);
    expect(token("--diff-added-bg")).toBe(a.editor!.added_bg);

    applyTheme(b);
    expect(token("--diff-added-bg")).toBe(b.editor!.added_bg);
  });

  it("falls back to derived accents when a theme ships no editor section", () => {
    // `parse_theme` always derives one, but `ThemeEditorData | null` is the
    // declared type, so the null branch must not throw.
    const theme = themes["github-light"];
    applyTheme(theme);
    const previousAdded = token("--diff-added-bg");

    applyTheme({ ...theme, editor: null });

    expect(token("--syntax-keyword")).toBe(theme.derived.accent_red);
    expect(token("--editor-line-highlight")).toBe("transparent");
    // Documents current behaviour: with no editor section there is no
    // derived diff background to fall back to, so the previous value
    // stands. Worth knowing if a theme ever ships `editor = null`.
    expect(token("--diff-added-bg")).toBe(previousAdded);
  });
});

// ── Mode-dependent overlay tints ────────────────────────────────────────
//
// These were hardcoded white-on-transparent at `:root` in app.css, which
// made the scrollbar thumb invisible on every light theme (white on white)
// and left the spinner with no visible track ring.

describe("applyTheme — scrollbar and spinner tints follow the mode", () => {
  it("uses dark-on-light tints for a light theme", () => {
    applyTheme(themes["github-light"]);

    // The exact alphas are a design choice; what must hold is that a light
    // theme gets a *dark* tint, because the failure mode was white on white.
    expect(token("--scrollbar-thumb")).toContain("rgba(0,0,0");
    expect(token("--scrollbar-thumb-hover")).toContain("rgba(0,0,0");
    expect(token("--spinner-track")).toContain("rgba(0,0,0");
  });

  it("makes the hover state stronger than the resting thumb", () => {
    applyTheme(themes["github-light"]);

    const alpha = (value: string): number =>
      Number.parseFloat(value.split(",").pop()!.replace(")", ""));
    expect(alpha(token("--scrollbar-thumb-hover"))).toBeGreaterThan(
      alpha(token("--scrollbar-thumb")),
    );
  });

  it("keeps light-on-dark tints for a dark theme", () => {
    // Built from the light fixture rather than adding a dark one: only the
    // mode drives these, and asserting that is the point.
    applyTheme({
      ...themes["github-light"],
      meta: { ...themes["github-light"].meta, mode: "dark" },
    });

    expect(token("--scrollbar-thumb")).toContain("rgba(255,255,255");
    expect(token("--spinner-track")).toContain("rgba(255,255,255");
  });
});

// ── The invariant lint cannot express ───────────────────────────────────
//
// `app.css`'s `:root` block legitimately holds white-based literals: they
// are the pre-theme defaults `applyTheme` overwrites. Stylelint's
// `function-disallowed-list` is therefore disabled for that block, which
// leaves one hole — a NEW white-based token added there, and forgotten in
// `computeOverlays`, is invisible in every light theme with no signal.
//
// That is not a lint rule, it's a cross-file invariant: every white-based
// default must have a per-mode override. This is the test for it.

import { readFileSync } from "node:fs";

describe("app.css white-based tokens all have per-mode overrides", () => {
  it("finds no white default that applyTheme leaves alone", () => {
    // Repo-root-relative: vitest runs from the project root, and
    // `import.meta.url` is not a file: URL under Vite's transform.
    const css = readFileSync("src/app.css", "utf8");

    // `--token: rgba(255, 255, 255, …)` / `rgb(255 255 255 …)`.
    const whiteDefaults = [
      ...css.matchAll(
        /^\s*(--[a-z0-9-]+)\s*:\s*[^;]*rgba?\(\s*255[\s,]+255[\s,]+255/gim,
      ),
    ].map((m) => m[1]);

    // Sanity: the scan must actually find the known dark defaults, or a
    // regex that matches nothing would make this test vacuous.
    expect(whiteDefaults.length).toBeGreaterThan(0);

    // Every one must be written by applyTheme in BOTH modes.
    applyTheme(themes["github-light"]);
    const lightMissing = whiteDefaults.filter((t) => token(t) === "");

    applyTheme({
      ...themes["github-light"],
      meta: { ...themes["github-light"].meta, mode: "dark" },
    });
    const darkMissing = whiteDefaults.filter((t) => token(t) === "");

    expect(
      { lightMissing, darkMissing },
      `these app.css tokens default to a white tint but applyTheme never ` +
        `overrides them, so they stay white-on-white in light themes`,
    ).toEqual({ lightMissing: [], darkMissing: [] });
  });
});
