/**
 * The `:root` block in `app.css` is the pre-theme first paint: the values
 * on screen for the frame between the window opening and the theme IPC
 * round-trip landing. Its own comment says they "mirror BeardGit Dark",
 * and nothing enforced that.
 *
 * They had drifted. Widening the elevation ramp moved `--bg-secondary` and
 * `--bg-toolbar`, splitting the border token moved `--border` and added
 * `--border-strong`, and raising the text rungs to WCAG AA on every
 * surface moved `--text-secondary` and `--text-muted` — none of which
 * reached `app.css`. The symptom is subtle (one frame of the wrong greys,
 * then a snap) which is exactly why it went unnoticed through three
 * separate changes.
 *
 * The fixture is generated by `storage::theme::tests::regenerate_theme_fixture`
 * and pinned by `test_theme_fixtures_match_live_serialization`, so this
 * compares against the bytes the frontend really receives.
 */

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import type { ThemeData } from "../types";
import fixtures from "./__fixtures__/themes.json";

const themes: Record<string, ThemeData> = fixtures;
const DEFAULT_THEME = "beardgit-dark";

/**
 * Custom properties declared in the first `:root { … }` block of
 * `app.css`. Later blocks are the per-mode overrides and media queries,
 * which are not first-paint defaults.
 */
function firstPaintTokens(): Map<string, string> {
  const css = readFileSync("src/app.css", "utf8");
  const start = css.indexOf(":root {");
  expect(start, "app.css must still open with a :root block").toBeGreaterThan(-1);
  const end = css.indexOf("\n}", start);
  expect(end, "unterminated :root block").toBeGreaterThan(start);

  const tokens = new Map<string, string>();
  for (const m of css.slice(start, end).matchAll(/^\s*(--[a-z0-9-]+)\s*:\s*([^;]+);/gim)) {
    tokens.set(m[1], m[2].trim());
  }
  return tokens;
}

describe("app.css first-paint defaults mirror the default theme", () => {
  const d = themes[DEFAULT_THEME].derived;
  const ed = themes[DEFAULT_THEME].editor;

  /**
   * Every token whose default is a literal colour that `applyTheme` later
   * overwrites from the theme payload, paired with the value it will be
   * overwritten *with*. Tokens defaulting to `var(…)` or an overlay
   * computed per mode are out of scope: they have no fixed literal to
   * drift from.
   */
  const MIRRORED: Array<[token: string, expected: string | null | undefined]> = [
    ["--bg-primary", d.bg_primary],
    ["--bg-secondary", d.bg_secondary],
    ["--bg-toolbar", d.bg_toolbar],
    ["--text-primary", d.text_primary],
    ["--text-secondary", d.text_secondary],
    ["--text-muted", d.text_muted],
    ["--accent-blue", d.accent_blue],
    ["--accent-green", d.accent_green],
    ["--accent-orange", d.accent_orange],
    ["--accent-purple", d.accent_purple],
    ["--accent-red", d.accent_red],
    ["--accent-primary", d.accent_primary],
    ["--accent-secondary", d.accent_secondary],
    ["--accent-tertiary", d.accent_tertiary],
    ["--border", d.border],
    ["--border-strong", d.border_strong],
    ["--selection", d.selection],
    // `[editor]` tokens. `--syntax-comment` is the one with no pinned
    // value in the default theme; `applyTheme` falls it back to
    // `text_secondary`, so that is what the default has to be.
    ["--syntax-keyword", ed?.syntax_keyword],
    ["--syntax-string", ed?.syntax_string],
    ["--syntax-comment", ed?.syntax_comment ?? d.text_secondary],
    ["--syntax-function", ed?.syntax_function],
    ["--syntax-type", ed?.syntax_type],
    ["--syntax-number", ed?.syntax_number],
    ["--syntax-operator", ed?.syntax_operator],
    ["--syntax-property", ed?.syntax_property],
    ["--diff-added-bg", ed?.added_bg],
    ["--diff-removed-bg", ed?.removed_bg],
    ["--editor-line-highlight", ed?.line_highlight],
  ];

  it("declares every mirrored token", () => {
    const tokens = firstPaintTokens();
    // Positive anchor first: a regex that matched nothing would make the
    // comparison below pass with two empty objects.
    expect(tokens.size).toBeGreaterThan(30);
    expect(MIRRORED.filter(([t]) => !tokens.has(t)).map(([t]) => t)).toEqual([]);
  });

  it("matches the default theme value for each of them", () => {
    const tokens = firstPaintTokens();
    const drifted = MIRRORED.filter(([token, expected]) => {
      expect(expected, `${token} has no value in the fixture`).toBeTruthy();
      return tokens.get(token)?.toLowerCase() !== String(expected).toLowerCase();
    }).map(([token, expected]) => `${token}: ${tokens.get(token)} → should be ${expected}`);

    expect(
      drifted,
      `app.css :root claims to mirror ${DEFAULT_THEME}; these no longer do, so the ` +
        `first frame paints colours the app never uses again`,
    ).toEqual([]);
  });
});
