[meta]
id = "dracula"
name = "Dracula"
mode = "dark"

[colors]
bg-primary = "#282a36"
bg-secondary = "#21222c"
bg-toolbar = "#343746"
text-primary = "#f8f8f2"
text-secondary = "#6272a4"
accent-blue = "#8be9fd"
accent-green = "#50fa7b"
accent-orange = "#ffb86c"
accent-purple = "#bd93f9"
accent-red = "#ff5555"
border = "#44475a"
selection = "#44475a66"
