[meta]
id = "gitlab-light"
name = "GitLab Light"
mode = "light"

[colors]
bg-primary = "#ffffff"
bg-secondary = "#fafafa"
bg-toolbar = "#ededed"
text-primary = "#303030"
text-secondary = "#737278"
accent-blue = "#1068bf"
accent-green = "#217645"
accent-orange = "#c17d10"
accent-purple = "#694cc0"
accent-red = "#dd2b0e"
border = "#dbdbdb"
selection = "#1068bf22"
