[meta]
id = "gitlab-light"
name = "GitLab Light"
mode = "light"
complementary = "gitlab-dark"

[colors]
background = "#ffffff"
foreground = "#303030"
black = "#303030"
red = "#dd2b0e"
green = "#108548"
yellow = "#a86800"
blue = "#1068bf"
magenta = "#7b439e"
cyan = "#0a7b83"
white = "#737278"
bright-black = "#89888d"
bright-red = "#c91c00"
bright-green = "#24663b"
bright-yellow = "#785300"
bright-blue = "#0d5eb0"
bright-magenta = "#694598"
bright-cyan = "#096e76"
bright-white = "#bfbfc3"
