[meta]
id = "monokai-pro"
name = "Monokai Pro"
mode = "dark"

[colors]
background = "#2d2a2e"
foreground = "#fcfcfa"
black = "#403e41"
red = "#ff6188"
green = "#a9dc76"
yellow = "#ffd866"
blue = "#78dce8"
magenta = "#ab9df2"
cyan = "#78dce8"
white = "#fcfcfa"
bright-black = "#727072"
bright-red = "#ff6188"
bright-green = "#a9dc76"
bright-yellow = "#ffd866"
bright-blue = "#78dce8"
bright-magenta = "#ab9df2"
bright-cyan = "#78dce8"
bright-white = "#fcfcfa"

[accents]
primary = "magenta"
secondary = "cyan"
tertiary = "yellow"
