[meta]
id = "solarized-dark"
name = "Solarized Dark"
mode = "dark"
complementary = "solarized-light"

[colors]
bg-primary = "#002b36"
bg-secondary = "#001e26"
bg-toolbar = "#073642"
text-primary = "#839496"
text-secondary = "#586e75"
accent-blue = "#268bd2"
accent-green = "#859900"
accent-orange = "#b58900"
accent-purple = "#6c71c4"
accent-red = "#dc322f"
border = "#073642"
selection = "#073642"
